##Worlds that collectors will work in
worlds:
  - 'world'
  - 'skyworld'

##Cost of each collector in /collector buy
collector-cost:
  drop: 10000 #Drop collectors will cost 10,000
  crop: 2500 #crop collectors will cost 2,500

##Set whether collectors can be destroyed by explosions or not
bomb-proof: true #if true, explosions will not affect collectors

#############################################
##Collector item Pricing

#Prices for the Drop Collector seller
mob-drops:
  BLAZE_ROD: 1.15
  STRING: 0.45
  SPIDER_EYE: 3.25
  GUNPOWDER: 1.1
  ROTTEN_FLESH: 0.4
  PRISMARINE_SHARD: 0.65
  PRISMARINE_CRYSTALS: 30.0
  ENDER_PEARL: 0.6
  GHAST_TEAR: 20.0
  MAGMA_CREAM: 0.6
  PHANTOM_MEMBRANE: 5.0
  ARROW: 0.05
  BONE: 0.04
  SHULKER_SHELL: 5.0
  SLIME_BALL: 1.2
  GLASS_BOTTLE: 0.45
  GLOWSTONE_DUST: 0.50
  STICK: 0.3
  SUGAR: 0.4
  COAL: 0.5
  REDSTONE: 1.1
  GOLD_NUGGET: 0.22
  GOLD_INGOT: 2.0

#Prices for the Crop Collector seller
crop-pricing:
  WHEAT: 1.0 #each wheat will be sold for 1 currency
  WHEAT_SEEDS: 0.2
  COCOA_BEANS: 0.5
  POTATO: 1.75
  BEETROOT: 1.65
  BEETROOT_SEEDS: 0.3
  SWEET_BERRIES: 1.5
  CARROT: 1.75
  NETHER_WART: 2.0
  POISONOUS_POTATO: 1.75
#############################################

############################################
##Collector Upgrades

##Capacity Upgrades (The max storage of a collector before it sells)
#You can add as many capacity levels as you want, just make sure it increases by one each level
#Also, don't forget to set a price for each capacity
storage-upgrades:
  1:
    items: 1000
    price: 0.0 #this price doesn't matter, they start off at this level
  2:
    items: 2500
    price: 10000.0
  3:
    items: 10000 #level 3 can hold a max of 10000 items
    price: 500000.0 #this upgrade costs 500,000.0
  4:
    items: 20000
    price: 1000000.0

##There are three fortune levels, you can set the price for each one
##Note: You start off at fortune level zero
fortune-prices:
  1: 10000.0 #Upgrade from zero to one costs 10,000
  2: 100000.0
  3: 2000000.0

############################################