name: ChunkCollector
version: ${project.version}
website: ggservers.com
author: Illuminatiiiiii
main: me.kodysimpson.chunkcollector.ChunkCollector
api-version: 1.15
softdepend:
  - vault
commands:
  collector:
    description: Commands for Chunk Collector
    usage: /collector