capacity:
  1: 1000 #1000 items
  2: 2500
  3: 5000
  4: 10000

capacity-prices:
  2: 10000
  3: 50000
  4: 200000

fortune-prices:
  1: 10000
  2: 100000
  3: 2000000

mob-drops:
  BLAZE_ROD: 5.0
  STRING: 5.0
  SPIDER_EYE: 5.0
  GUNPOWDER: 5.0
  ROTTEN_FLESH: 5.0
  PRISMARINE_SHARD: 5.0
  PRISMARINE_CRYSTALS: 5.0
  ENDER_PEARL: 5.0
  GHAST_TEAR: 5.0
  MAGMA_CREAM: 5.0
  PHANTOM_MEMBRANE: 5.0
  ARROW: 5.0
  BONE: 5.0
  SHULKER_SHELL: 5.0
  SLIME_BALL: 5.0
  GLASS_BOTTLE: 5.0
  GLOWSTONE_DUST: 5.0
  STICK: 5.0
  SUGAR: 5.0
  COAL: 5.0
  REDSTONE: 5.0
  GOLD_NUGGET: 5.0
  GOLD_INGOT: 5.0