name: ChunkCollector
version: 1.0-SNAPSHOT
main: me.kodysimpson.chunkcollector.ChunkCollector
api-version: 1.15
softdepend:
  - vault
commands:
  collector:
    description: Commands for Chunk Collector
    usage: /collector