name: ChunkCollector
version: 1.0.6
website: ggservers.com
author: Illuminatiiiiii
main: me.kodysimpson.chunkcollector.ChunkCollector
api-version: 1.13
softdepend:
  - vault
commands:
  collector:
    description: Commands for Chunk Collector
    usage: /collector